updated travis with deployment

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,4 +1,3 @@
-# Neuroconductor Template
 language: r
 sudo: false
 cache: packages
@@ -7,108 +6,79 @@ use_bioc: true
 bioc_required: true
 cran: http://cran.rstudio.com
 dist: precise
-
 os:
-  - linux
-  - osx
-
+- linux
+- osx
 env:
   global:
   - R_BUILD_ARGS="--no-build-vignettes --no-manual"
   - R_CHECK_ARGS="--as-cran --install-args=--build"
   - RGL_USE_NULL=TRUE
   - PROJECT_NAME=neuroconductor
-
 before_install:
-  - export PROJ_DIR=`basename $PWD`
-  - fname=travis_helpers.sh
-  - wget -O ${fname} http://bit.ly/travis_helpers
-  - cat ${fname}; source ${fname}; rm ${fname}  
-  - cat DESCRIPTION
-  - export PACKAGE_NAME=`package_name`  
-  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
-  - Rscript -e 'source("https://install-github.me/mangothecat/callr")'
-  - remove_neuroc_packages
-  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
-  # does all the clang exports
-  - x=`export_clang_cxx`; eval ${x}
-  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
-  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"  
-  - clang_cxx  
-  - export cmake_version="3.4"
-  - cmake --version
-  - x=`cmake_setup`; echo "${x}"; eval ${x};
-  - cmake --version
-  - export ants_user=neuroconductor
-  - echo "Installing Missing Deps ITKR"
-  - install_missing_remote_deps ${ants_user}/ITKR
-  - gh_binary_install ${ants_user}/ITKR ;
-  - if [[ "${PACKAGE_NAME}" != "ITKR" ]]; 
-    then
-      echo "Installing Missing Deps ANTsRCore" ;
-      install_missing_remote_deps ${ants_user}/ANTsRCore;
-      gh_binary_install ${ants_user}/ANTsRCore ;
-    fi
-  - if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; 
-    then
-      echo "Installing Missing Deps ANTsR" ;
-      install_missing_remote_deps ${ants_user}/ANTsR ;
-      gh_binary_install ${ants_user}/ANTsR ;
-    fi    
-  - if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; 
-    then 
-      export _R_CHECK_FORCE_SUGGESTS_=0 ;
-    fi
-  - cat DESCRIPTION
-  - install_remotes_no_dep
-  - cat DESCRIPTION
-  - echo $PATH ;
-  - install_deps_no_suggests
-
+- export PROJ_DIR=`basename $PWD`
+- fname=travis_helpers.sh
+- wget -O ${fname} http://bit.ly/travis_helpers
+- cat ${fname}; source ${fname}; rm ${fname}
+- cat DESCRIPTION
+- export PACKAGE_NAME=`package_name`
+- export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
+- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
+- remove_neuroc_packages
+- export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
+- x=`export_clang_cxx`; eval ${x}
+- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
+- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
+- clang_cxx
+- export cmake_version="3.4"
+- cmake --version
+- x=`cmake_setup`; echo "${x}"; eval ${x};
+- cmake --version
+- export ants_user=neuroconductor
+- echo "Installing Missing Deps ITKR"
+- install_missing_remote_deps ${ants_user}/ITKR
+- gh_binary_install ${ants_user}/ITKR ;
+- if [[ "${PACKAGE_NAME}" != "ITKR" ]]; then echo "Installing Missing Deps ANTsRCore"
+  ; install_missing_remote_deps ${ants_user}/ANTsRCore; gh_binary_install ${ants_user}/ANTsRCore
+  ; fi
+- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; then echo
+  "Installing Missing Deps ANTsR" ; install_missing_remote_deps ${ants_user}/ANTsR
+  ; gh_binary_install ${ants_user}/ANTsR ; fi
+- if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; then export _R_CHECK_FORCE_SUGGESTS_=0 ;
+  fi
+- cat DESCRIPTION
+- install_remotes_no_dep
+- cat DESCRIPTION
+- echo $PATH ;
+- install_deps_no_suggests
 script:
-  # - source ~/.R/Makevars
-  - x=`export_clang_cxx`; eval ${x}
-  - travis_wait 100 R CMD build ${R_BUILD_ARGS} . 
-  - rm -f travis_wait*.log
-  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
-  - ls
-  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
-  - rm -f travis_wait*.log
-  - check_fail
-  - check_warnings
-  # - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))" ;
-  # - grep -q -R "WARNING" "${RCHECK_DIR}/00check.log" ; if [[ $? -eq 0 ]]; error 1; fi  
-  # - if [[ ${#TRAVIS_TAG} -eq 0 ]]; 
-  #   then 
-  #   travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; 
-  #   fi
-
+- x=`export_clang_cxx`; eval ${x}
+- travis_wait 100 R CMD build ${R_BUILD_ARGS} .
+- rm -f travis_wait*.log
+- PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
+- ls
+- travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+- rm -f travis_wait*.log
+- check_fail
+- check_warnings
 after_success:
-  - cat ${PACKAGE_NAME}.Rcheck/00install.out
-  - cat ${PACKAGE_NAME}.Rcheck/00check.log
-
+- cat ${PACKAGE_NAME}.Rcheck/00install.out
+- cat ${PACKAGE_NAME}.Rcheck/00check.log
 after_failure:
-  - cat ${PACKAGE_NAME}.Rcheck/00install.out
-  - cat ${PACKAGE_NAME}.Rcheck/00check.log
-
-# so no overwrite of linux build
+- cat ${PACKAGE_NAME}.Rcheck/00install.out
+- cat ${PACKAGE_NAME}.Rcheck/00check.log
 before_deploy:
-  - if [ "$TRAVIS_OS_NAME" = "osx" ];
-    then
-      rm -f *.tar.gz;
-    fi
+- if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -f *.tar.gz; fi
+after_deploy:
+- if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsRCore" ]]; Rscript -e 'covr::coveralls(type = "all")' ; fi
+
 
 deploy:
   provider: releases
   skip_cleanup: true
   api_key:
-    secure: Do4qaIvPGwUN2WCIbEm40VmRS+fSYWZmqU4c72xZ6iyiv+b+hDlCN/G7R5r9kdNbmrfi9VNkO/qdzQRTNo1MbPlHsAf3FvSRRNxFQHP4mIUTNi285qnjC2fM6hImMNWIhIAbizooJcousNldsmSQdIfPFaxO8Egur9dAtBf4ycz1M0D4DB4tvG7lkjrJx0ufbYMAKRQp5LuYJZWGZ2kItJjnDfBDzHEb4J88iUfzbKkczBlSlqKnjWsIkHLn+s74y75iglrS4z5d5DX+RT5bQPx8Cl66Up6j0N8bHaYN6EPFkdxtN4g4RdBWZ40CXHaUEHVnPzya3pQB/1sjptNCqxNGo9w7jCTJVrCkURMkLP+B3mwq7GfjaZ4ezyMTIA3pigQCsT9PrUujvw0ahluzaQYPjP/WC4ad2NVRGZF6A4IEhWOfiUyl80hYbm8lcB2r5CvTzA0EH314UoKhZt6G9BNanp37hsc57P6Zya80Nbd75KMOuJGVZG6yz5FXDC8wANGukt1eb+ThhNl9BhDwCQemnb4nYA/aRWOt+AgrW193OByamE0+rCegxdVUTaLVh6YMMcPg2goKS8MdertfEO8D81wkr5g4JZXtG1votalN9DjxhF70bzhdaz6vXTgJCY0LPigmxUCgKciz4vrHGbbul3l1BDLBx3FGylteZSA=
+    secure: ATTq8B5qry2hLOsbYRXb6kwG3O0JgSQjmkP9aCsiLkZbBx1ivFIsy8WTGg6UGvSOjY3DMNYR266oyIxKutGmnLFh38C8bVoGdquhDSOAXUjeb4Mz3aNglXHOxGhcD/xdlcJToGFkxwYAuEgTHoAaRo6KQUKV5AqEO8Vw1qx9DVfg8RdfrlkH7CXoxUr65SFvBsEMuwXH9VlLuPkMd0HrRWWeo255ASltN5N9l5EEFZQ+DGwyeRum1HwW7VBuJvIuWnOvZVcTwxYw6vqu4FEWinUbtnW9GpQ/FUjFj6DlA651mA0LuK3RrmngGhdbaJn51ct8NdH7bnkaS6/UuJT02Yzqhj4D7pQK6uLosVO15oh1RySOJygE1rVS9EtufRxgH4fqa5YQqvnczTKwh0WHpt3EDuEKhLdfQxEjr+daEr+XqFofdCBaRUWU9YjeXy77hxEbTi9EN7IHNIj7yqeOI2yVsCvYVhl7C9n72ndJTDw5CRIXH6LL4rBaLzMfrhq4uIrq6F3y1nRMVyEpH2f1C670DH3OP9JcMTYaFeWs1XLsd9pCGrale7PGHnnQeBp9lqdWieGtjhQvskZbnsy9OKqipV20//+GZtmabQIS9OzCctUbxWvOAdu2g067XgBA/sRE4t/pFaK+vH+TS7WG8800oJAtZoNj983p376xkvs=
   file_glob: true
   file: ${PACKAGE_NAME}*.t*gz
   on:
     tags: true
-
-after_deploy:
-  - if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsRCore" ]]; 
-      Rscript -e 'covr::coveralls(type = "all")' ;
-    fi
